###############################################################################
# Generate Personal Information File                                          #
#                                                                             #
# Last Modified: 2022-Apr-26                                                  #
###############################################################################
library(data.table)
library(arrow)
library(dplyr)
###############################################################################
### README ####################################################################
###############################################################################
# This file outputs individual's background information that would never change
# OUTPUT FIELDS:
#   - `ID`:      (chars) individual's ID.
#   (1)
#   - `F_ID`:    (char)  father's ID.
#   - `F_ID_S`:  (int)   father's gender. 1: male; 2: female.
#   - `M_ID`:    (char)  mother's ID
#   - `M_ID_S`:  (int)   mother's gender. 1: male; 2: female.
#   - `S_ID`:    (char)  Spouse's ID
#   - `S_ID_S`:  (int)   spouse's gender. 1: male; 2: female.

###############################################################################
### PREAMBLE ##################################################################
###############################################################################

rm(list=ls()); gc()
source("E:/H112057/arrow/arrow_20230831/arrow_helpers.R")

### Variables #################################################################
DISK        <- "E"
READ.DIR    <- paste0(DISK, ":/H112057/parquet")
SAVE.DIR    <- paste0(DISK, ":/H112057/CleanData/processed_data")
LOGFILE     <- "PersInfo.log" %>% paste0(SAVE.DIR,.)
YEARS       <- (89L:110L) %>% as.character()
MONTHS      <- c(1:12) %>% as.character() %>% str_pad(width=2,side='left',pad='0')

### Useful Independent Functions ##############################################
date.time       <- function ()       { return( format(Sys.time(),"(%Y/%b/%d) %X") ) }
console.log     <- function ( ... ) { cat(format(Sys.time(),"(%Y/%b/%d) %X"),...,"\n") }
agree           <- function ( vec ) { length(unique(vec))==1 }



###############################################################################
### FUNCTIONS #################################################################
###############################################################################
MAIN.load.year.data <- function(year, month) {
  ## Read enrollment data for one year, selecting only ID, ID_S, and ID_BIRTHDAY
  message(paste("Start to load:", year, month))
  start_time <- Sys.time()
  dt_enrol <- open_nhi("ENROL", year, month) %>%
    select(ID, ID_S, ID_BIRTHDAY, ID_ROC, ID_STATUS) %>% 
    mutate(ID_STATUS := as.character(ID_STATUS),
           ID_ROC := as.character(ID_ROC)) %>% 
    filter(ID_STATUS == "1" & ID_ROC == "0") %>% # Only keep those who are currently in NHI and pass error detection
    collect() %>%
    as.data.table()
  end_time <- Sys.time()
  print(end_time - start_time)
  
  cat('Finished reading at', date.time(), "\n", file=LOGFILE, append=TRUE) # <log>
  return(dt_enrol)
  
}

gender.distribution <- function(dt) {
  # Create a wide form data.table with ID being rows and gender count being cols
  
  dt_gender <- dt[, .(ID, ID_S)]
  dt_gender <- gender(dt_birth)
  dt_gender <- gender[, .(count = .N,
                           ID_BIRTHDAY = fist(ID_BIRTHDAY)), by = ID]
  dt_gender <- dt_gender[count == 1]
  
  return(dt_gender)
}

gender.proportion <- function(dt) {
  # Calculate the according proportion of each individual's gender being male,
  # female, or other in all the data.
  # Input dt must be something generated by gender.distribution().
  setnames(dt, c("ID", "ID_S_1", "ID_S_2", "ID_S_999"), c("ID", "male", "female", "others"))
  dt <- dt[, .(male = sum(male, na.rm = TRUE), female = sum(female, na.rm = TRUE), others = sum(others, na.rm = TRUE)), by = ID]
  dt[, `:=`(
    proportion_male = male / rowSums(.SD, na.rm = TRUE),
    proportion_female = female / rowSums(.SD, na.rm = TRUE),
    proportion_other = others / rowSums(.SD, na.rm = TRUE)
  ), .SDcols = c("male", "female", "others")]
  
  dt[, gender_valid := pmax(proportion_male, proportion_female)]
  dt[, gender := fifelse(male >= female, 1, 0)]
  dt[, `:=`(male = NULL, female = NULL, others = NULL)]
  return(dt)
}

compare.birthday <- function(dt, col_name) {
  ## Remove sample with weird birthday
  dt_birth <- dt[!is.na(ID_BIRTHDAY) & ID_BIRTHDAY %/% 10000000 >= 1, .(ID, ID_BIRTHDAY)]
  dt_birth <- distinct(dt_birth)
  dt_birth <- dt_birth[, .(count = .N,
                           ID_BIRTHDAY = fist(ID_BIRTHDAY)), by = ID]
  dt_birth <- dt_birth[count == 1]
  
  return(dt_birth)
}
###############################################################################
### MAIN ######################################################################
###############################################################################
general.log <- file(paste0(SAVE.DIR,"general.log"),open="wt") # <general.log>
sink(general.log, append=TRUE, type="message") # <general.log>
sink(general.log, append=TRUE, type="output") # <general.log>


birrthday_annual_data_list <- list()
gender_annual_data_list <- list()
for (year in YEARS) {
  year_data <- list()
  for (month in 1:12) {
    monthly_dt <- MAIN.load.year.data(year, month)
    year_data <- c(year_data, list(monthly_dt))
  }
  data <- rbindlist(year_data)
  
  message("Gender")
  start_time <- Sys.time()
  dt_gender <- gender.distribution(data)
  gender_annual_data_list <- c(gender_annual_data_list, list(dt_gender))
  end_time <- Sys.time()
  print(end_time - start_time)
  
  message("Birthday")
  start_time <- Sys.time()
  dt_birthday <- compare.birthday(data, "ID_BIRTHDAY")
  birthday_annual_data_list <- c(birthday_annual_data_list, list(dt_dist))
  end_time <- Sys.time()
  print(end_time - start_time)
  
  message("Write")
  start_time <- Sys.time()
  write_parquet(dt_gender, paste0(SAVE.DIR, "/temp_data/gender", year, ".parquet"))
  write_parquet(dt_birthday, paste0(SAVE.DIR, "/temp_data/birthday", year, ".parquet"))
  end_time <- Sys.time()
  print(end_time - start_time)
}

gender <- rbindlist(gender_annual_data_list, fill = TRUE) %>% gender.proportion()

birthday <- rbindlist(birthday_annual_data_list, fill = TRUE) %>% year.to.year.compare.birthday()



data <- open_dataset(paste0(SAVE.DIR, "/PersInfo.parquet")) %>% collect() %>% as.data.table()
write_parquet(data, paste0(SAVE.DIR, "/PersInfo.parquet"))



closeAllConnections() # <general.log>
